version: '3.8'

services:
  api:
    image: ghcr.io/lochlanodlum/uni-swe-agile-backend:latest
    platform: linux/arm64
    env_file: .env
    ports:
      - '80:8000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/locationlocator'
