version: '3.8'
services:
  api:
    build:
      context: ./backend
    env_file: .env
    ports:
      - '80:80'
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: local-testing-password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: locationlocator
      AUTH_HASH_SECRET_KEY: SOMETHING

  db:
    image: postgres:15
    restart: always
    env_file: .env
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local-testing-password
      POSTGRES_DB: locationlocator
# volumes:
#   postgres_data:
