name: Build and Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install --upgrade pip
          # install both prod & dev deps (linters, pytest, etc.)
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check import order (isort)
        working-directory: backend
        run: isort . --check --diff

      - name: Check formatting (black)
        working-directory: backend
        run: black . --check

      - name: Run linter (flake8)
        working-directory: backend
        run: flake8 .

      - name: Run tests (pytest)
        working-directory: backend
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install CDK dependencies
        run: |
          cd cdk
          npm ci

      - name: Deploy CDK stack (builds image and uploads to ECR)
        run: |
          cd cdk
          npx cdk deploy --require-approval never
